name: Builds, tests & co

on:
  - push
  - pull_request

permissions: read-all

jobs:
  bwrap-test:
    runs-on: ubuntu-latest

    steps:
      - name: Run a privileged OCaml container
        run: |
          docker run --rm --privileged ocaml/opam:ubuntu-ocaml-4.11 bash -c '
            apt update &&
            apt install -y bubblewrap &&
            sysctl -w kernel.unprivileged_userns_clone=1 || true &&
            echo "Trying bubblewrap..." &&
            bwrap --dev-bind / / echo "Bubblewrap works!"'
    # container:
    #   image: ocaml/opam:ubuntu-ocaml-4.11
    #   options: --privileged

    # steps:
    #   - name: Update apt and install bubblewrap
    #     run: |
    #       sudo apt update
    #       sudo apt install -y bubblewrap

    #   - name: Try bubblewrap
    #     run: |
    #       sysctl -w kernel.unprivileged_userns_clone=1 || true
    #       bwrap --dev-bind / / echo "✅ Bubblewrap works!"

  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: See if privileged Docker works 
  #       run: |
  #         docker run --privileged ubuntu echo "Hello from privileged Docker"

  #     - name: Test bubblewrap in privileged container
  #       run: |
  #         docker run --rm --privileged ubuntu bash -c '
  #           apt update && apt install -y bubblewrap &&
  #           sysctl -w kernel.unprivileged_userns_clone=1 &&
  #           bwrap --dev-bind / / echo "Bubblewrap works!"'
        
      # - name: Checkout tree
      #   uses: actions/checkout@v4

      # - name: Set-up OCaml (4.11)
      #   uses: ocaml/setup-ocaml@v3
      #   with:
      #     ocaml-compiler: 4.11

      # - name: Add Coq OPAM repositories
      #   run: |
      #     opam repo add coq-released https://coq.inria.fr/opam/released
      #     opam repo add coq-core-dev https://coq.inria.fr/opam/core-dev
      #     opam repo add coq-extra-dev https://coq.inria.fr/opam/extra-dev

      # - name: Test bwrap
      #   run: bwrap --dev-bind / / echo "bubblewrap is working!"

